image: ruby:2.3

theme:
  stage: build
  script:
  - gem install jekyll
  - jekyll build -d public
  - gem build editorial_jekyll_theme.gemspec
  artifacts:
    paths:
    - public
    - "*.gem"
  only:
  - master